SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60

COLOR_BACKGROUND = (10, 10, 40)
COLOR_DRONE = (255, 255, 255)

DEFAULT_DRONE_COUNT = 50
DRONE_RADIUS = 5
DRONE_SPEED = 3
DRONE_MASS = 1

# --- Follow Mouse Config ---
MOUSE_ATTRACTION_FORCE = 0.05
MOUSE_MAX_SPEED = 5
FRICTION = 0.98

# --- Boids Flocking Config ---
BOIDS_PERCEPTION_RADIUS = 100
BOIDS_MIN_SPEED = 1
BOIDS_MAX_SPEED = 4

BOIDS_SEPARATION_WEIGHT = 1.7
BOIDS_ALIGNMENT_WEIGHT = 1.0
BOIDS_COHESION_WEIGHT = 1.0
BOIDS_WANDER_STRENGTH = 0.4
