SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60

COLOR_BACKGROUND = (10, 10, 40)
COLOR_DRONE = (255, 255, 255)

DEFAULT_DRONE_COUNT = 50
DRONE_RADIUS = 5
DRONE_SPEED = 3
DRONE_MASS = 1

# --- Follow Mouse Config ---
MOUSE_ATTRACTION_FORCE = 0.05
MOUSE_MAX_SPEED = 5
FRICTION = 0.98

# --- Boids Flocking Config ---
BOIDS_PERCEPTION_RADIUS = 75
BOIDS_SEPARATION_RADIUS = 30
BOIDS_MIN_SPEED = 2
BOIDS_MAX_SPEED = 5

BOIDS_SEPARATION_WEIGHT = 2.0
BOIDS_ALIGNMENT_WEIGHT = 0.6
BOIDS_COHESION_WEIGHT = 0.01

# Wall avoidance
BOIDS_WALL_MARGIN = 50
BOIDS_WALL_TURN_STRENGTH = 2.0
